{
    "openapi": "3.1.0",
    "info": {
        "title": "API Системы Управления Домашней Библиотекой",
        "version": "0.10.0"
    },
    "servers": [
        {
            "url": "http://localhost/api/v1",
            "description": "Локальный сервер."
        }
    ],
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Восстановление пароля",
                "description": "Запрос на получение ссылки по email на восстановление пароля",
                "operationId": "c9c7469e9ce95024f66ad3214c2edece",
                "requestBody": {
                    "description": "JSON объект учетных данных пользователя для сброса пароля",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "email"
                                ],
                                "properties": {
                                    "email": {
                                        "description": "email",
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "email": "john.doe@example.com"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение.",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Мы выслали вам ссылку для сброса пароля по электронной почте!"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение.",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Пользователь не найден."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация",
                "description": "Запрос на идентификацию и авторизацию пользователя.",
                "operationId": "1d79bc8c412efee515f071b286fe7e45",
                "requestBody": {
                    "description": "JSON объект учетных данных пользователя",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "description": "email",
                                        "type": "string"
                                    },
                                    "password": {
                                        "description": "Пароль.",
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "email": "john.doe@example.com",
                                "password": "password"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "access_token": {
                                            "description": "Токен доступа.",
                                            "type": "string"
                                        },
                                        "token_type": {
                                            "description": "Тип токена.",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "access_token": "2|ioWWhr1rvgJuMGGzpdGD1jagfVaC5JSQV0uIQll480242318",
                                    "token_type": "Bearer"
                                }
                            }
                        }
                    },
                    "422": {
                        "$ref": "#/components/responses/login_validation_error"
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "tags": [
                    "auth"
                ],
                "summary": "Выход",
                "description": "Запрос на выход пользователя из системы.",
                "operationId": "1bfd9d171bebc74065d4dfc78d9d0df1",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Выход из системы успешно выполнен"
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация",
                "description": "Запрос на регистрацию пользователя.",
                "operationId": "7682aaf57789a5a6d60dd1a77d5765b4",
                "requestBody": {
                    "description": "JSON объект данных пользователя",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "email",
                                    "password",
                                    "password_confirmation",
                                    "name"
                                ],
                                "properties": {
                                    "name": {
                                        "description": "Имя пользователя",
                                        "type": "string",
                                        "maxLength": 255
                                    },
                                    "email": {
                                        "description": "email",
                                        "type": "string",
                                        "maxLength": 255
                                    },
                                    "password": {
                                        "description": "Пароль.",
                                        "type": "string",
                                        "minLength": 6
                                    },
                                    "password_confirmation": {
                                        "description": "Подтверждение пароля.",
                                        "type": "string",
                                        "minLength": 6
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "john.doe@example.com",
                                    "password": "password",
                                    "password_confirmation": "password",
                                    "name": "John Doe"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "name": {
                                            "description": "Имя пользователя.",
                                            "type": "string",
                                            "maxLength": 255
                                        },
                                        "email": {
                                            "description": "email.",
                                            "type": "string",
                                            "maxLength": 255
                                        },
                                        "password": {
                                            "description": "Пароль.",
                                            "type": "string",
                                            "minLength": 6
                                        },
                                        "password_confirmation": {
                                            "description": "Подтверждение пароля.",
                                            "type": "string",
                                            "minLength": 6
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "name": "John Doe",
                                    "email": "john.doe@example.com",
                                    "id": 1
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение об ошибке"
                                        },
                                        "errors": {
                                            "description": "Массив ошибок",
                                            "properties": {
                                                "name": {
                                                    "type": "array",
                                                    "items": {
                                                        "properties": {
                                                            "name": {
                                                                "description": "Невалидное имя пользователя",
                                                                "type": "string"
                                                            }
                                                        },
                                                        "type": "object"
                                                    }
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "The name field is required.",
                                        "errors": {
                                            "name": [
                                                "The name field is required."
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Сброс пароля",
                "description": "Запрос на сброс и получение нового пароля",
                "operationId": "f9dd9444674bc34de8899ef4f0a64fbb",
                "requestBody": {
                    "description": "JSON объект учетных данных пользователя для сброса пароля",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "email",
                                    "password",
                                    "password_confirmation",
                                    "token"
                                ],
                                "properties": {
                                    "token": {
                                        "description": "token сброса пароля",
                                        "type": "string"
                                    },
                                    "email": {
                                        "description": "email",
                                        "type": "string"
                                    },
                                    "password": {
                                        "description": "Новый пароль.",
                                        "type": "string",
                                        "minLength": 6
                                    },
                                    "password_confirmation": {
                                        "description": "Подтверждение нового пароля.",
                                        "type": "string",
                                        "minLength": 6
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "token": "bb0bdfe208d0bc60f567fcb168fe561dca5ac9581bb4fd8e97e6037b2276194d",
                                "email": "john.doe@example.com",
                                "password": "123456",
                                "password_confirmation": "123456"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение.",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Пароль успешно сброшен."
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "error": {
                                            "description": "Сообщение об ошибке",
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "error": "Не удалось сбросить пароль."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/author": {
            "post": {
                "tags": [
                    "author"
                ],
                "summary": "Создание автора",
                "description": "Запрос на создание автора.",
                "operationId": "d8405d97bcaba675a45464231c6bf103",
                "requestBody": {
                    "description": "JSON объект для создания нового автора",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "surname",
                                    "name"
                                ],
                                "properties": {
                                    "surname": {
                                        "description": "Фамилия",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "name": {
                                        "description": "Имя",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "patronymic": {
                                        "description": "Отчество",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "surname": "Иванов",
                                "name": "Иван",
                                "patronymic": "Иванович"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Автор успешно создан.",
                                            "type": "string"
                                        },
                                        "author": {
                                            "description": "Информация о авторе.",
                                            "properties": {
                                                "id": {
                                                    "description": "Идентификатор автора.",
                                                    "type": "integer"
                                                },
                                                "surname": {
                                                    "description": "Фамилия автора",
                                                    "type": "string"
                                                },
                                                "name": {
                                                    "description": "Имя автора",
                                                    "type": "string"
                                                },
                                                "patronymic": {
                                                    "description": "Отчество автора",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Автор успешно создан.",
                                    "author": {
                                        "id": 1,
                                        "surname": "Иванов",
                                        "name": "Иван",
                                        "patronymic": "Иванович"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            }
        },
        "/author/{author}": {
            "get": {
                "tags": [
                    "author"
                ],
                "summary": "Информация о авторе",
                "description": "Запрос на вывод детальной информации о авторе",
                "operationId": "872cb5747e3ffe66d42f637db41ef2b2",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/author"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "description": "Данные об авторе.",
                                            "properties": {
                                                "id": {
                                                    "description": "ID автора",
                                                    "type": "integer"
                                                },
                                                "surname": {
                                                    "description": "Фамилия.",
                                                    "type": "string"
                                                },
                                                "name": {
                                                    "description": "Имя.",
                                                    "type": "string"
                                                },
                                                "patronymic": {
                                                    "description": "Отчество.",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "data": {
                                        "id": 1,
                                        "surname": "Иванов",
                                        "name": "Иван",
                                        "patronymic": "Иванович"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            },
            "put": {
                "tags": [
                    "author"
                ],
                "summary": "Обновление о автора",
                "description": "Запрос на обновление автора.",
                "operationId": "d223434169b0f354af538ca60fc3e979",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/author"
                    }
                ],
                "requestBody": {
                    "description": "JSON объект для обновления автора",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "surname",
                                    "name"
                                ],
                                "properties": {
                                    "surname": {
                                        "description": "Фамилия",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "name": {
                                        "description": "Имя",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "patronymic": {
                                        "description": "Отчество",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "surname": "Иванов",
                                "name": "Иван",
                                "patronymic": "Иванович"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение.",
                                            "type": "string"
                                        },
                                        "author": {
                                            "description": "Информация о авторе.",
                                            "properties": {
                                                "id": {
                                                    "description": "ID автора.",
                                                    "type": "integer"
                                                },
                                                "surname": {
                                                    "description": "Фамилия автора",
                                                    "type": "string"
                                                },
                                                "name": {
                                                    "description": "Имя автора",
                                                    "type": "string"
                                                },
                                                "patronymic": {
                                                    "description": "Отчество автора",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Автор успешно обновлен.",
                                    "author": {
                                        "surname": "Иванов",
                                        "name": "Иван",
                                        "patronymic": "Иванович"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    }
                }
            },
            "delete": {
                "tags": [
                    "author"
                ],
                "summary": "Удаление автора",
                "description": "Запрос на удаление автора.",
                "operationId": "832182e4af387f173cc8dfec02c2b151",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/author"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            }
        },
        "/book": {
            "post": {
                "tags": [
                    "book"
                ],
                "summary": "Создание новой книги",
                "description": "Запрос на создание книги.",
                "operationId": "173f3a6722b2f15ec94dfd8ef13a627b",
                "requestBody": {
                    "description": "JSON объект для создания новой книги",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "title",
                                    "author_id"
                                ],
                                "properties": {
                                    "title": {
                                        "description": "Название книги",
                                        "type": "string"
                                    },
                                    "author_id": {
                                        "description": "ID автора книги.",
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "maxLength": 150
                            },
                            "example": {
                                "title": "Как войти в IT.",
                                "author_id": 1
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение об успешном создании книги.",
                                            "type": "string"
                                        },
                                        "book": {
                                            "description": "Информация о книге.",
                                            "properties": {
                                                "id": {
                                                    "description": "ID книги.",
                                                    "type": "integer"
                                                },
                                                "author": {
                                                    "description": "Информация о авторе книги.",
                                                    "properties": {
                                                        "id": {
                                                            "description": "ID автора.",
                                                            "type": "integer"
                                                        },
                                                        "surname": {
                                                            "description": "Фамилия автора",
                                                            "type": "string"
                                                        },
                                                        "name": {
                                                            "description": "Имя автора",
                                                            "type": "string"
                                                        },
                                                        "patronymic": {
                                                            "description": "Отчество автора",
                                                            "type": "string"
                                                        }
                                                    },
                                                    "type": "object"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Книга успешно создана.",
                                    "book": {
                                        "id": 1,
                                        "title": "Как войти в IT.",
                                        "author": {
                                            "id": 1,
                                            "surname": "Иванов",
                                            "name": "Иван",
                                            "patronymic": "Иванович"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "422": {
                        "$ref": "#/components/responses/book_validation_errors"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            }
        },
        "/book/{book}": {
            "get": {
                "tags": [
                    "book"
                ],
                "summary": "Информация о книге",
                "description": "Запрос на вывод детальной информации о конкретной книге.",
                "operationId": "b801f1686b5ae67663a85dff5d95b7d4",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/book"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "data": {
                                            "description": "Данные о книге",
                                            "properties": {
                                                "id": {
                                                    "description": "ID книги",
                                                    "type": "integer"
                                                },
                                                "title": {
                                                    "description": "Название книги",
                                                    "type": "string"
                                                },
                                                "author": {
                                                    "description": "Автор книги.",
                                                    "properties": {
                                                        "id": {
                                                            "description": "ID автора",
                                                            "type": "integer"
                                                        },
                                                        "surname": {
                                                            "description": "Фамилия автора",
                                                            "type": "string"
                                                        },
                                                        "name": {
                                                            "description": "Имя автора",
                                                            "type": "string"
                                                        },
                                                        "patronymic": {
                                                            "description": "Отчество автора",
                                                            "type": "string"
                                                        }
                                                    },
                                                    "type": "object"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "data": {
                                        "id": 1,
                                        "title": "Как войти в IT.",
                                        "author": {
                                            "id": 1,
                                            "surname": "Иванов",
                                            "name": "Иван",
                                            "patronymic": "Иванович"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            },
            "put": {
                "tags": [
                    "book"
                ],
                "summary": "Обновление книги",
                "description": "Запрос на обновление информации о конкретной книге.",
                "operationId": "0ecd2c1eec148b134fe72215da5461e4",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/book"
                    }
                ],
                "requestBody": {
                    "description": "JSON объект для создания новой книги",
                    "content": {
                        "application/json": {
                            "schema": {
                                "description": "Тело запроса.",
                                "required": [
                                    "title",
                                    "author_id"
                                ],
                                "properties": {
                                    "title": {
                                        "description": "Название книги",
                                        "type": "string"
                                    },
                                    "author_id": {
                                        "description": "ID автора книги.",
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "maxLength": 150
                            },
                            "example": {
                                "title": "Как выйти из IT.",
                                "author_id": 2
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Сообщение об успешном создании книги.",
                                            "type": "string"
                                        },
                                        "book": {
                                            "description": "Информация о книге.",
                                            "properties": {
                                                "id": {
                                                    "description": "ID книги.",
                                                    "type": "integer"
                                                },
                                                "author": {
                                                    "description": "Информация о авторе книги.",
                                                    "properties": {
                                                        "id": {
                                                            "description": "ID автора.",
                                                            "type": "integer"
                                                        },
                                                        "surname": {
                                                            "description": "Фамилия автора",
                                                            "type": "string"
                                                        },
                                                        "name": {
                                                            "description": "Имя автора",
                                                            "type": "string"
                                                        },
                                                        "patronymic": {
                                                            "description": "Отчество автора",
                                                            "type": "string"
                                                        }
                                                    },
                                                    "type": "object"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "message": "Книга успешно обновлена.",
                                    "book": {
                                        "id": 1,
                                        "title": "Как выйти из IT.",
                                        "author": {
                                            "id": 2,
                                            "surname": "Пупкин",
                                            "name": "Василий",
                                            "patronymic": "Васильевич"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "422": {
                        "$ref": "#/components/responses/book_validation_errors"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            },
            "delete": {
                "tags": [
                    "book"
                ],
                "summary": "Удаление книги",
                "description": "Запрос на удаление конкретной книги.",
                "operationId": "a7b1998ab63ff811b087e83357d8a02e",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/book"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "$ref": "#/components/responses/not_found"
                    },
                    "401": {
                        "$ref": "#/components/responses/unauthenticated"
                    }
                }
            }
        }
    },
    "components": {
        "responses": {
            "not_found": {
                "description": "Not Found",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "Сообщение",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "message": "Запрашиваемый ресурс не найден"
                        }
                    }
                }
            },
            "book_validation_errors": {
                "description": "Unprocessable Content",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "Сообщение об ошибках.",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Перечисление ощибок валидации",
                                    "properties": {},
                                    "type": "object"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "message": "The title field is required. (and 1 more error)",
                            "errors": {
                                "title": [
                                    "The title field is required."
                                ],
                                "author_id": [
                                    "The author_id field is required."
                                ]
                            }
                        }
                    }
                }
            },
            "unauthenticated": {
                "description": "Unauthorized",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "Сообщение",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "message": "Unauthenticated."
                        }
                    }
                }
            },
            "login_validation_error": {
                "description": "Unprocessable Content",
                "content": {
                    "application/json": {
                        "schema": {
                            "properties": {
                                "message": {
                                    "description": "Сообщение",
                                    "type": "string"
                                },
                                "errors": {
                                    "description": "Массив ошибок",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "example": {
                            "message": "Предоставленные учетные данные неверны.",
                            "errors": [
                                [
                                    "Предоставленные учетные данные неверны."
                                ]
                            ]
                        }
                    }
                }
            }
        },
        "parameters": {
            "book": {
                "name": "book",
                "in": "path",
                "description": "Идентификатор книги",
                "required": true,
                "schema": {
                    "type": "integer"
                }
            },
            "author": {
                "name": "author",
                "in": "path",
                "description": "Идентификатор автора",
                "required": true,
                "schema": {
                    "type": "integer"
                }
            }
        },
        "securitySchemes": {
            "sanctum": {
                "type": "apiKey",
                "description": "Enter token in format (Bearer <token>)",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "tags": [
        {
            "name": "book",
            "description": "Все эндпоинты API, относящиеся к книгам"
        },
        {
            "name": "auth",
            "description": "Все эндпоинты API, относящиеся к аутентификации пользователя"
        },
        {
            "name": "author",
            "description": "Все эндпоинты API, относящиеся к авторам"
        }
    ],
    "security": [
        {
            "sanctum": []
        }
    ]
}